[tox]
requires = virtualenv<20.22.0
envlist = py{27,38,39,310,311}-{linux,macos,windows}, lint, docker
skip_missing_interpreters=true

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
platform = lin: linux
           mac: darwin
           win: win32
passenv = USERNAME
changedir = {toxinidir}
commands =
    {envpython} --version
    py.test --cov-report term-missing --cov python_hosts
deps =
    enum-compat
    PyYAML>=3.11
    pytest>=3.0.3
    pytest-cov>=2.4.0

[testenv:py27]
deps =
    enum-compat
    PyYAML==5.4.1
    pytest>=3.0.3,<5
    pytest-cov>=2.4.0,<3
commands =
    {envpython} --version
    py.test --cov-report term-missing --cov python_hosts
